binance:
  symbols:
    - btcusdt
    - ethusdt
    - bnbusdt

  streams:
    - "@kline_1m"
 #   - "@trade"
 #   - "@miniTicker"
 #   - "@ticker"
 #   - "@depth10"
 #   - "@depth@100ms"

  globalStreams:
  #  - "!miniTicker@arr"
  #  - "!ticker@arr"